version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/src
hooks:
  AfterInstall:
    - location: src/scripts/restart_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: src/scripts/start_flask.sh
      timeout: 300
      runas: root
