version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install -r requirements.txt
      - pip install gunicorn boto3
  build:
    commands:
      - echo "Build phase complete"
  post_build:
    commands:
      - echo "Post-build phase complete"
artifacts:
  files:
    - '**/*'
