version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
artifacts:
  files:
    - appspec.yml
    - scripts/*
    - app.py
    - templates/*
    - requirements.txt
    - vinyl_records.db
