name: Create and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-2                     # Set this to your AWS region, e.g., us-west-1
  EB_BUCKET_NAME: vly2121                   # Set this to your S3 bucket for storing application versions
  IMAGE_TAG: ${{ github.sha }}              # Image tag based on Git commit SHA

permissions:
  contents: read

jobs:
  deploy:
    name: Create and Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Elastic Beanstalk CLI
      run: |
        # Install the Elastic Beanstalk CLI using pip
        pip install awsebcli
        eb --version  # Verify installation of eb CLI

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Prepare application for Elastic Beanstalk
      run: |
        # Create a ZIP file of the application to upload to Elastic Beanstalk
        zip -r application.zip .  # Create a zip of the project folder

    - name: Upload application to S3
      run: |
        aws s3 cp application.zip s3://${{ env.EB_BUCKET_NAME }}/application.zip
        # Register the application version with Elastic Beanstalk
        aws elasticbeanstalk create-application-version \
          --application-name MyDynamicApp \
          --version-label ${{ env.IMAGE_TAG }} \
          --source-bundle S3Bucket=${{ env.EB_BUCKET_NAME }},S3Key=application.zip

    - name: Initialize Elastic Beanstalk Application
      run: |
        # Initialize Elastic Beanstalk for Python 3.12
        eb init -p python-3.12 --region ${{ env.AWS_REGION }} --no-verify-ssl

    - name: Create Elastic Beanstalk Environment
      run: |
        # Check if the environment exists using eb status
        if eb list | grep -q 'MyDynamicEnv'; then
          echo "Environment already exists."
        else
          echo "Creating Elastic Beanstalk environment..."
          eb create MyDynamicEnv --region ${{ env.AWS_REGION }} --single
        fi

    - name: Deploy to Elastic Beanstalk
      run: |
        # Deploy the application to Elastic Beanstalk using the version we registered
        eb deploy MyDynamicEnv --no-verify-ssl --label ${{ env.IMAGE_TAG }}
